import { mock } from 'bun:test';
import type { Mock } from 'bun:test';
import type { Ulak } from '../../server/messaging';

/**
 * A Ulak.NameSpace stub whose methods are all Bun mock functions
 *
 * Extends Ulak.NameSpace so any method added to the interface in the future
 * breaks this file's compilation instead of silently drifting out of sync.
 */
export interface TestUlakNameSpace<T extends string = string> extends Ulak.NameSpace<T> {
  broadcast: Mock<(data: any) => Promise<void>>;
  to: Mock<(room: string, data: any) => Promise<void>>;
  toSocket: Mock<(socketId: string, data: any) => Promise<void>>;
  toMany: Mock<(rooms: string[], data: any) => Promise<void>>;
  getSocketCount: Mock<() => number>;
}

/**
 * Creates a typed Ulak namespace stub for tests
 *
 * Use it as an explicit override for @Inject(ulak(...)) fields when you want
 * a fully typed mock instead of the automatic deep mock generated by
 * mockComponent.
 *
 * @param path - The namespace path the stub reports (defaults to '/')
 * @returns Ulak.NameSpace implementation with all methods mocked
 *
 * @example
 * ```typescript
 * import { mockComponent, createTestUlakStub } from '@asenajs/asena/test';
 *
 * const statsChannel = createTestUlakStub('/ws/public/stats');
 *
 * const { instance } = mockComponent(UserService, {
 *   overrides: { statsChannel },
 * });
 *
 * await instance.createAnonUser('John');
 *
 * expect(statsChannel.broadcast).toHaveBeenCalledWith({
 *   action: 'update',
 *   data: { newUser: 1 },
 * });
 * ```
 */
export function createTestUlakStub<T extends string = string>(path: T = '/' as T): TestUlakNameSpace<T> {
  return {
    path,
    broadcast: mock(async () => undefined),
    to: mock(async () => undefined),
    toSocket: mock(async () => undefined),
    toMany: mock(async () => undefined),
    getSocketCount: mock(() => 0),
  };
}
