export enum ComponentType {
  COMPONENT = 'COMPONENT',
  SERVICE = 'SERVICE',
  CONTROLLER = 'CONTROLLER',
  SCHEDULE = 'SCHEDULE',
  MIDDLEWARE = 'MIDDLEWARE',
  WEBSOCKET = 'WEBSOCKET',
  CONFIG = 'CONFIG',
}
