export enum ComponentType {
  COMPONENT = 'COMPONENT',
  SERVICE = 'SERVICE',
  CONTROLLER = 'CONTROLLER',
  FRONTEND_CONTROLLER = 'FRONTEND_CONTROLLER',
  SCHEDULE = 'SCHEDULE',
  MIDDLEWARE = 'MIDDLEWARE',
  WEBSOCKET = 'WEBSOCKET',
  CONFIG = 'CONFIG',
  EVENT = 'EVENT',
  POST_PROCESSOR = 'POST_PROCESSOR',
  MESSAGE_CONTROLLER = 'MESSAGE_CONTROLLER',
}
