export enum ComponentType {
  COMPONENT = 'COMPONENT',
  SERVICE = 'SERVICE',
  CONTROLLER = 'CONTROLLER',
  DATABASE = 'DATABASE',
  SERVER_SERVICE = 'SERVER_SERVICE',
  SCHEDULE = 'SCHEDULE',
  MIDDLEWARE = 'MIDDLEWARE',
}
